application: uw-moca
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
